/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostedFieldsRouteImport } from './routes/hosted-fields'
import { Route as HostedPageRouteImport } from './routes/hosted-page'
import { Route as PaymentReturnRouteImport } from './routes/payment/return'
import { Route as SummaryFailureRouteRouteImport } from './routes/summary/failure/route'
import { Route as SummarySuccessRouteRouteImport } from './routes/summary/success/route'
import { Route as PaymentActionActionIdRouteImport } from './routes/payment/action.$actionId'
import { Route as SummaryFailureIndexRouteImport } from './routes/summary/failure/index'
import { Route as SummarySuccessIndexRouteImport } from './routes/summary/success/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedFieldsRoute = HostedFieldsRouteImport.update({
  id: '/hosted-fields',
  path: '/hosted-fields',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedPageRoute = HostedPageRouteImport.update({
  id: '/hosted-page',
  path: '/hosted-page',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryFailureRouteRoute = SummaryFailureRouteRouteImport.update({
  id: '/summary/failure',
  path: '/summary/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const SummarySuccessRouteRoute = SummarySuccessRouteRouteImport.update({
  id: '/summary/success',
  path: '/summary/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentActionActionIdRoute = PaymentActionActionIdRouteImport.update({
  id: '/payment/action/$actionId',
  path: '/payment/action/$actionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryFailureIndexRoute = SummaryFailureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SummaryFailureRouteRoute,
} as any)
const SummarySuccessIndexRoute = SummarySuccessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SummarySuccessRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hosted-fields': typeof HostedFieldsRoute
  '/hosted-page': typeof HostedPageRoute
  '/summary/failure': typeof SummaryFailureRouteRouteWithChildren
  '/summary/success': typeof SummarySuccessRouteRouteWithChildren
  '/payment/return': typeof PaymentReturnRoute
  '/payment/action/$actionId': typeof PaymentActionActionIdRoute
  '/summary/failure/': typeof SummaryFailureIndexRoute
  '/summary/success/': typeof SummarySuccessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hosted-fields': typeof HostedFieldsRoute
  '/hosted-page': typeof HostedPageRoute
  '/payment/return': typeof PaymentReturnRoute
  '/payment/action/$actionId': typeof PaymentActionActionIdRoute
  '/summary/failure': typeof SummaryFailureIndexRoute
  '/summary/success': typeof SummarySuccessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hosted-fields': typeof HostedFieldsRoute
  '/hosted-page': typeof HostedPageRoute
  '/summary/failure': typeof SummaryFailureRouteRouteWithChildren
  '/summary/success': typeof SummarySuccessRouteRouteWithChildren
  '/payment/return': typeof PaymentReturnRoute
  '/payment/action/$actionId': typeof PaymentActionActionIdRoute
  '/summary/failure/': typeof SummaryFailureIndexRoute
  '/summary/success/': typeof SummarySuccessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hosted-fields'
    | '/hosted-page'
    | '/summary/failure'
    | '/summary/success'
    | '/payment/return'
    | '/payment/action/$actionId'
    | '/summary/failure/'
    | '/summary/success/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hosted-fields'
    | '/hosted-page'
    | '/payment/return'
    | '/payment/action/$actionId'
    | '/summary/failure'
    | '/summary/success'
  id:
    | '__root__'
    | '/'
    | '/hosted-fields'
    | '/hosted-page'
    | '/summary/failure'
    | '/summary/success'
    | '/payment/return'
    | '/payment/action/$actionId'
    | '/summary/failure/'
    | '/summary/success/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostedFieldsRoute: typeof HostedFieldsRoute
  HostedPageRoute: typeof HostedPageRoute
  SummaryFailureRouteRoute: typeof SummaryFailureRouteRouteWithChildren
  SummarySuccessRouteRoute: typeof SummarySuccessRouteRouteWithChildren
  PaymentReturnRoute: typeof PaymentReturnRoute
  PaymentActionActionIdRoute: typeof PaymentActionActionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted-fields': {
      id: '/hosted-fields'
      path: '/hosted-fields'
      fullPath: '/hosted-fields'
      preLoaderRoute: typeof HostedFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted-page': {
      id: '/hosted-page'
      path: '/hosted-page'
      fullPath: '/hosted-page'
      preLoaderRoute: typeof HostedPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary/failure': {
      id: '/summary/failure'
      path: '/summary/failure'
      fullPath: '/summary/failure'
      preLoaderRoute: typeof SummaryFailureRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary/success': {
      id: '/summary/success'
      path: '/summary/success'
      fullPath: '/summary/success'
      preLoaderRoute: typeof SummarySuccessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/action/$actionId': {
      id: '/payment/action/$actionId'
      path: '/payment/action/$actionId'
      fullPath: '/payment/action/$actionId'
      preLoaderRoute: typeof PaymentActionActionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary/failure/': {
      id: '/summary/failure/'
      path: '/'
      fullPath: '/summary/failure/'
      preLoaderRoute: typeof SummaryFailureIndexRouteImport
      parentRoute: typeof SummaryFailureRouteRoute
    }
    '/summary/success/': {
      id: '/summary/success/'
      path: '/'
      fullPath: '/summary/success/'
      preLoaderRoute: typeof SummarySuccessIndexRouteImport
      parentRoute: typeof SummarySuccessRouteRoute
    }
  }
}

interface SummaryFailureRouteRouteChildren {
  SummaryFailureIndexRoute: typeof SummaryFailureIndexRoute
}

const SummaryFailureRouteRouteChildren: SummaryFailureRouteRouteChildren = {
  SummaryFailureIndexRoute: SummaryFailureIndexRoute,
}

const SummaryFailureRouteRouteWithChildren =
  SummaryFailureRouteRoute._addFileChildren(SummaryFailureRouteRouteChildren)

interface SummarySuccessRouteRouteChildren {
  SummarySuccessIndexRoute: typeof SummarySuccessIndexRoute
}

const SummarySuccessRouteRouteChildren: SummarySuccessRouteRouteChildren = {
  SummarySuccessIndexRoute: SummarySuccessIndexRoute,
}

const SummarySuccessRouteRouteWithChildren =
  SummarySuccessRouteRoute._addFileChildren(SummarySuccessRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostedFieldsRoute: HostedFieldsRoute,
  HostedPageRoute: HostedPageRoute,
  SummaryFailureRouteRoute: SummaryFailureRouteRouteWithChildren,
  SummarySuccessRouteRoute: SummarySuccessRouteRouteWithChildren,
  PaymentReturnRoute: PaymentReturnRoute,
  PaymentActionActionIdRoute: PaymentActionActionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
